// src/components/MangaCard.tsx

import React from 'react';
import { Link } from 'react-router-dom';
import { Manga } from '../services/api';
import { Heart } from 'lucide-react';

interface MangaCardProps {
  manga: Manga;
  isFavorite: boolean;
  onToggleFav: (e: React.MouseEvent) => void;
}

export default function MangaCard({ manga, isFavorite, onToggleFav }: MangaCardProps) {
  return (
    <div className="group relative flex flex-col h-full bg-white dark:bg-dark-surface rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-shadow">
      <Link to={`/manga/${manga.mangaId}`} className="relative w-full aspect-[2/3] overflow-hidden bg-gray-200 dark:bg-gray-800">
        <img 
          src={manga.coverImage} 
          alt={manga.title} 
          loading="lazy" 
          className="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105"
        />
        
        {manga.genre && manga.genre.length > 0 && (
          <div className="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-2">
            <span className="text-[10px] text-white bg-brand-600/90 px-1.5 py-0.5 rounded-md backdrop-blur-sm">
              {manga.genre[0]}
            </span>
          </div>
        )}
      </Link>

      <div className="p-2.5 flex flex-col flex-1">
        <h3 className="text-sm font-semibold text-gray-900 dark:text-gray-100 line-clamp-2 leading-tight mb-1">
          {manga.title}
        </h3>
        
        <div className="mt-auto flex items-center justify-between pt-2">
          <button 
            onClick={onToggleFav} 
            className="text-gray-400 hover:text-red-500 active:scale-95 transition-transform p-1 -ml-1"
          >
            <Heart size={20} className={isFavorite ? "fill-red-500 text-red-500" : ""} />
          </button>
          
          <span className="text-[10px] text-gray-500 dark:text-gray-400 font-medium tracking-wide">INFO</span>
        </div>
      </div>
    </div>
  );
}

// src/components/ui/manga-card.component.ts

import { Component, Input, Output, EventEmitter, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Manga } from '../../services/manga.service';
import { StorageService } from '../../services/storage.service';

@Component({
  selector: 'app-manga-card',
  imports: [CommonModule, RouterLink],
  template: `
    <div class="group relative flex flex-col h-full bg-white dark:bg-dark-surface rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-shadow">
      <!-- Image Container -->
      <a [routerLink]="['/manga', manga.mangaId]" class="relative w-full aspect-[2/3] overflow-hidden bg-gray-200 dark:bg-gray-800">
        <!-- Changed to eager loading as images are now preloaded by the service -->
        <img [src]="manga.coverImage" [alt]="manga.title" loading="eager" class="w-full h-full object-cover transition-transform duration-500 group-hover:scale-105">
        
        <!-- Genre Tag (First only) -->
        @if (manga.genre && manga.genre.length > 0) {
          <div class="absolute bottom-0 left-0 right-0 bg-gradient-to-t from-black/80 to-transparent p-2">
            <span class="text-[10px] text-white bg-brand-600/90 px-1.5 py-0.5 rounded-md backdrop-blur-sm">
              {{ manga.genre[0] }}
            </span>
          </div>
        }
      </a>

      <!-- Content -->
      <div class="p-2.5 flex flex-col flex-1">
        <h3 class="text-sm font-semibold text-gray-900 dark:text-gray-100 line-clamp-2 leading-tight mb-1">
          {{ manga.title }}
        </h3>
        
        <div class="mt-auto flex items-center justify-between pt-2">
          <button (click)="toggleFav.emit($event)" class="text-gray-400 hover:text-red-500 active:scale-95 transition-transform p-1 -ml-1">
            <svg xmlns="http://www.w3.org/2000/svg" [class.fill-red-500]="isFavorite" [class.text-red-500]="isFavorite" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-5 h-5">
              <path stroke-linecap="round" stroke-linejoin="round" d="M21 8.25c0-2.485-2.099-4.5-4.688-4.5-1.935 0-3.597 1.126-4.312 2.733-.715-1.607-2.377-2.733-4.313-2.733C5.1 3.75 3 5.765 3 8.25c0 7.22 9 12 9 12s9-4.78 9-12z" />
            </svg>
          </button>
          
          <span class="text-[10px] text-gray-500 dark:text-gray-400 font-medium tracking-wide">INFO</span>
        </div>
      </div>
    </div>
  `
})
export class MangaCardComponent {
  @Input({ required: true }) manga!: Manga;
  @Input({ required: true }) isFavorite: boolean = false;
  @Output() toggleFav = new EventEmitter<Event>();
}
